services:
  api:
    image: deveegbo/fastapi
    ports:
      - 80:8000
    environment:
      - DATABASE_HOSTNAME=${db_host}
      - DATABASE_PORT=${db_port}
      - DATABASE_PASSWORD=${db_password}
      - DATABASE_NAME=${dn_name}
      - DATABASE_USERNAME=${db_user}
      - SECRET_KEY=${jwt_secret_key}
      - ALGORITHM=${algorithm}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${access_token_expiry_minutes}

    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${db_password}
      - POSTGRES_DB=${db_name}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: