services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # env_file:
    #     - ./.env
    environment:
      - DATABASE_HOSTNAME=${db_host}
      - DATABASE_PORT=${db_port}
      - DATABASE_PASSWORD=${db_password}
      - DATABASE_NAME=${db_name}
      - DATABASE_USERNAME=${db_user}
      - SECRET_KEY=${jwt_secret_key}
      - ALGORITHM=${algorithm}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${access_token_expiry_minutes}

    command: uvicorn app.main_w_sqlalchemy:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD={db_password}
      - POSTGRES_DB={db_name}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: