name: My Social Media API Workflow

on: [push, pull_request]

jobs:
  job1:
    env:
      DB_HOST: ${{secrets.DB_HOST}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_USER: ${{secrets.DB_USER}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_PORT: ${{secrets.DB_PORT}}
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRY_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRY_MINUTES}}
      TEST_DB_NAME: ${{secrets.TEST_DB_NAME}}
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
          POSTGRES_DB: ${{secrets.TEST_DB_NAME}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v5
      - name:  Installing python version 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: Installing all dependencies
        run: pip install -r requirements.txt
      - name: Testing with PyTest
        run: pytest
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Set up Docker  Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Image digest
        run: echo ${{steps.docker_build.outputs.digest}}